### PR TITLE
use fPIC so crossguid can be added to another library

### PR DESCRIPTION
**Pull request by vancemiller**

### CODE REVIEW

**Comment by graeme-hill** [comment]
Will this work on windows? Maybe should use the cmake syntax instead?

```
set_property(TARGET crossguid PROPERTY POSITION_INDEPENDENT_CODE ON)
```

**Comment by vancemiller** [comment]
I can't test this change on other platforms but if there is an alternative that preserves compatibility and allows the library to link with another library that would be perfect.

**Comment by gabyx** [comment]
I use
```
ExternalProject_Add(crossguid
                            PREFIX              "${ExecutionGraph_EXTERNAL_BUILD_DIR}/crossguid"
                            GIT_REPOSITORY      "${URL}"
                            GIT_TAG             master
                            GIT_SHALLOW         ON
                            TIMEOUT 10
                            UPDATE_DISCONNECTED  ON
                            CMAKE_ARGS "-DCMAKE_BUILD_TYPE=Release" 
                                       "-DCMAKE_VERBOSE_MAKEFILE=ON" 
                                       "-DCROSSGUID_TESTS=OFF" 
                                       "-DCMAKE_INSTALL_PREFIX=${INSTALL_DIR}" 
                                       "-DCMAKE_POSITION_INDEPENDENT_CODE=ON"
                            INSTALL_DIR "${INSTALL_DIR}")
``
https://github.com/gabyx/ExecutionGraph/blob/3861e32fc539804b6c275a66a0f43470c3a8a21c/cmake/external/FindCrossGUIDLib.cmake#L26

**Comment by graeme-hill** [comment]
Closed in favor of #46

**Pull request closed without merging**
