### PR TITLE
[Android] Added newGuid() overloading to support multithread invocations

### PR DESCRIPTION
**Pull request by thedilletante**
The changes consist of two parts:
1) Enabled ability to call `newGuid()` function between different jni calls and from different threads. For the latter `newGuid(JNIEnv *)` overloading was introduced. So, users that called `newGuid()` from single thread aren't affected. Users who want to call method everywhere should provide appropriate `JNIEnv` pointer for the current context. There was added sort of validation into `newGuid()` method to detect illegal usage from multiple threads on debug builds (if wrong `JNIEnv` is provided `assert()` will crash the app).
2) Migrated to **Gradle** build system for Android instead of Ant. Gradle system is suggested by developer.android.com (https://developer.android.com/studio/build/index.html), natively supported by Android Studio and support CMake integration. Also, test cases were added into application to verify `newGuid()` invocation from different threads. *This changes are minor, and if ant build system is preferable for the project, I can discard it*

### CODE REVIEW

**Comment by graeme-hill** [comment]
Note to self: this is to resolve #23

**Comment by graeme-hill** [comment]
Looks guid. I tested on non-android to make sure it still works. Thanks for the fix.

**Comment by graeme-hill** [comment]
Wow... I actually did mean to say "Looks good"... haha

**Comment by thedilletante** [comment]
Yes, it's really looks guid :)
Thanks for the merge.

**Pull request merged**
